**학습/테스트 데이터셋 분리 - train_test_split()**

In [7]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris_data = load_iris()
df_clf = DecisionTreeClassifier()
train_data = iris_data.data
train_label = iris_data.target
df_clf.fit(train_data, train_label)

pred = df_clf.predict(train_data)
print('예측 정확도 ',accuracy_score(train_label, pred))

예측 정확도  1.0

In [ ]:
df_clf = DecisionTreeClassifier()
iris_data = load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)

In [10]:
df_clf.fit(X_train, y_train)
pred = df_clf.predict(X_test)
accuracy = accuracy_score(y_test, pred)
print('예측 정확도 : {0:.4f}'.format(accuracy))

예측 정확도 : 0.9556

**넘파이 ndarray뿐만 아니라 판다스 DataFrame/Series도 train_test_split()으로 분할 가능**

In [11]:
import pandas as pd
iris_df = pd.DataFrame(data=iris_data.data, columns=iris_data.feature_names)
iris_df['target'] = iris_data.target
iris_df.head(3)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0

In [13]:
ftr_df = iris_df.iloc[:, :-1]
tgt_df = iris_df.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(ftr_df, tgt_df, test_size=0.3, random_state=121)

In [14]:
print(type(X_train), type(y_train), type(X_test), type(y_test))

<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'> <class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>

In [17]:
df_clf = DecisionTreeClassifier()
df_clf.fit(X_train, y_train)
pred = df_clf.predict(X_test)
accuracy = accuracy_score(y_test, pred)
print('예측 정확도 : {0:.4f}'.format(accuracy))

예측 정확도 : 0.9556

**교차 검증**

- K Fold

In [ ]:
from sklearn.model_selection import KFold
import numpy as np

iris_data = load_iris()
features = iris_data.data
label = iris_data.target
df_clf = DecisionTreeClassifier(random_state=151)

# 5개의 폴드로 나누는 KFold 객체 생성
kfold = KFold(n_splits=5)
cv_accuracy = []
print('붓꽃 데이터 세트 크기:', features.shape[0])

붓꽃 데이터 세트 크기: 150

In [31]:
n_iter = 0


for train_index, test_index in kfold.split(features) :  # 5번 반복
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    # 학습 및 예측
    df_clf.fit(X_train,y_train)
    prer = df_clf.predict(X_test)
    n_iter += 1
    
    # 반복 시 마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, prer), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print(f'{n_iter} 교차 검증 정확도 {accuracy}, 학습 데이터 크기: {train_size}, 검증 데이터 크기: {test_size}')
    print('#{0} 검증 세트 인덱스 {1}'.format(n_iter, test_index))
    print(train_index)
    
    cv_accuracy.append(accuracy)

print('평균 검증 정확도:', np.mean(cv_accuracy))

1 교차 검증 정확도 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#1 검증 세트 인덱스 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
2 교차 검증 정확도 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#2 검증 세트 인덱스 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
3 교차 검증 정확도 0.8667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#3 검증 세트 인덱스 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
4 교차 검증 정확도 0.9333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#4 검증 세트 인덱스 [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
5 교차 검증 정확도 0.7667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#5 검증 세트 인덱스 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]
평균 검증 정확도: 0.91334

- Stratified K Fold

In [40]:
import pandas as pd

iris = load_iris()

iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()
iris_df.head(3)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0

In [41]:
k_fold = KFold(n_splits=3)
n_iter = 0
for train_index, test_index in k_fold.split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('{0} 교차 검증 '.format(n_iter))
    print(f'학습 레이블 데이터 분포 {label_train.value_counts()} ')
    print(f'검증 레이블 데이터 분포 {label_test.value_counts()} ')

1 교차 검증
학습 레이블 데이터 분포 label
1    50
2    50
Name: count, dtype: int64
검증 레이블 데이터 분포 label
0    50
Name: count, dtype: int64
2 교차 검증
학습 레이블 데이터 분포 label
0    50
2    50
Name: count, dtype: int64
검증 레이블 데이터 분포 label
1    50
Name: count, dtype: int64
3 교차 검증
학습 레이블 데이터 분포 label
0    50
1    50
Name: count, dtype: int64
검증 레이블 데이터 분포 label
2    50
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df['label']) :
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('{0} 교차 검증 '.format(n_iter))
    print(f'학습 레이블 데이터 분포 {label_train.value_counts()} ')
    print(f'검증 레이블 데이터 분포 {label_test.value_counts()} ')

1 교차 검증
학습 레이블 데이터 분포 label
2    34
0    33
1    33
Name: count, dtype: int64
검증 레이블 데이터 분포 label
0    17
1    17
2    16
Name: count, dtype: int64
2 교차 검증
학습 레이블 데이터 분포 label
1    34
0    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포 label
0    17
2    17
1    16
Name: count, dtype: int64
3 교차 검증
학습 레이블 데이터 분포 label
0    34
1    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포 label
1    17
2    17
0    16
Name: count, dtype: int64

 - cross_val_score()

In [44]:
from sklearn.model_selection import cross_val_score

iris = load_iris()
df_clf = DecisionTreeClassifier(random_state=156)

data = iris.data
label = iris.target

# 성능 지표는 accuracy로 설정하고, 3개의 폴드로 나누어 교차 검증 수행
scores = cross_val_score(df_clf,data,label,scoring='accuracy', cv=3)
print('교차 검증별 정확도:', np.round(scores, 4))
print('평균 검증 정확도:', np.round(np.mean(scores), 4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667

- GridSearchCV

In [47]:
from sklearn.model_selection import GridSearchCV

iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=121)

d_tree = DecisionTreeClassifier()

# parameter 들을 dictionary 형태로 정의
parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [52]:
# refit=True가 default 값으로 설정되어 있어, True 이면 최적의 파라미터로 재학습을 수행함
grid_tree =GridSearchCV(d_tree,param_grid=parameters,
                        cv=3, refit=True, return_train_score=True)

grid_tree.fit(X_train, y_train)

# GridSearchCV 의 결과는 cv_results_ 라는 딕셔너리 형태로 저장됨, 이를 DataFrame으로 변환
scores_df = pd.DataFrame(grid_tree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score','split0_test_score','split1_test_score','split2_test_score']]

,params,mean_test_score,rank_test_score,split0_test_score,split1_test_score,split2_test_score
0,"{'max_depth': 1, 'min_samples_split': 2}",0.700000,5,0.700,0.7,0.70
1,"{'max_depth': 1, 'min_samples_split': 3}",0.700000,5,0.700,0.7,0.70
2,"{'max_depth': 2, 'min_samples_split': 2}",0.958333,3,0.925,1.0,0.95
3,"{'max_depth': 2, 'min_samples_split': 3}",0.958333,3,0.925,1.0,0.95
4,"{'max_depth': 3, 'min_samples_split': 2}",0.975000,1,0.975,1.0,0.95
5,"{'max_depth': 3, 'min_samples_split': 3}",0.975000,1,0.975,1.0,0.95

In [53]:
grid_tree.cv_results_

{'mean_fit_time': array([0.00063451, 0.0004669 , 0.0004286 , 0.0002985 , 0.00028642,
        0.0002927 ]),
 'std_fit_time': array([9.20977639e-05, 8.49950995e-06, 4.58641722e-05, 1.35374733e-05,
        2.37888170e-06, 2.08070207e-05]),
 'mean_score_time': array([0.00046412, 0.00030772, 0.00030128, 0.00020766, 0.00021052,
        0.00021736]),
 'std_score_time': array([5.98328777e-05, 3.09836132e-05, 4.58658247e-05, 2.48535407e-06,
        1.85486999e-05, 3.48190906e-05]),
 'param_max_depth': masked_array(data=[1, 1, 2, 2, 3, 3],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_min_samples_split': masked_array(data=[2, 3, 2, 3, 2, 3],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'params': [{'max_depth': 1, 'min_samples_split': 2},
  {'max_depth': 1, 'min_samples_split': 3},
  {'max_depth': 2, 'min_samples_split': 2},
  {'max_depth': 2, 'min_samples_split': 3},
  {'max_depth': 3, 'min_samples_split': 2},
  {'max_depth': 3, 'min_samples_split': 3}],
 'split0_test_score': array([0.7  , 0.7  , 0.925, 0.925, 0.975, 0.975]),
 'split1_test_score': array([0.7, 0.7, 1. , 1. , 1. , 1. ]),
 'split2_test_score': array([0.7 , 0.7 , 0.95, 0.95, 0.95, 0.95]),
 'mean_test_score': array([0.7       , 0.7       , 0.95833333, 0.95833333, 0.975     ,
        0.975     ]),
 'std_test_score': array([1.11022302e-16, 1.11022302e-16, 3.11804782e-02, 3.11804782e-02,
        2.04124145e-02, 2.04124145e-02]),
 'rank_test_score': array([5, 5, 3, 3, 1, 1], dtype=int32),
 'split0_train_score': array([0.7   , 0.7   , 0.975 , 0.975 , 0.9875, 0.9875]),
 'split1_train_score': array([0.7   , 0.7   , 0.9375, 0.9375, 0.9625, 0.9625]),
 'split2_train_score': array([0.7   , 0.7   , 0.9625, 0.9625, 0.9875, 0.9875]),
 'mean_train_score': array([0.7       , 0.7       , 0.95833333, 0.95833333, 0.97916667,
        0.97916667]),
 'std_train_score': array([1.11022302e-16, 1.11022302e-16, 1.55902391e-02, 1.55902391e-02,
        1.17851130e-02, 1.17851130e-02])}

In [59]:
print('최적 하이퍼 파라미터:', grid_tree.best_params_)
print('최고 예측 정확도:', grid_tree.best_score_)

# refit=True로 설정되어 있어, GridSearchCV 객체가 fit() 수행 시 학습이 완료된 Estimator를 반환함
pred = grid_tree.predict(X_test)
print('테스트 세트 예측 정확도 {0:.4f} '.format(accuracy_score(y_test, pred)))

최적 하이퍼 파라미터: {'max_depth': 3, 'min_samples_split': 2}
최고 예측 정확도: 0.975
테스트 세트 예측 정확도 0.9667

In [61]:
estimator = grid_tree.best_estimator_

pred = estimator.predict(X_test)
print('테스트 세트 예측 정확도 {0:.4f} '.format(accuracy_score(y_test, pred)))

테스트 세트 예측 정확도 0.9667